name: food_repository
description: A repository to provide items data (in-memory for now).
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter